import { nanoid } from 'nanoid'


const FlavoredDishes = {
    Italian: [
        { id: nanoid(), name: "Pizza Margherita", description: "Classic Italian pizza with tomato, mozzarella, and basil." },
        { id: nanoid(), name: "Pasta Carbonara", description: "Spaghetti with eggs, cheese, pancetta, and black pepper." },
        { id: nanoid(), name: "Risotto alla Milanese", description: "Creamy saffron-flavored risotto." },
        { id: nanoid(), name: "Lasagna", description: "Layered pasta dish with meat, cheese, and tomato sauce." },
        { id: nanoid(), name: "Tiramisu", description: "Coffee-flavored dessert with mascarpone cheese and ladyfingers." },
        { id: nanoid(), name: "Ossobuco", description: "Braised veal shanks with gremolata." },
        { id: nanoid(), name: "Caprese Salad", description: "Tomato, mozzarella, and basil salad with olive oil." },
        { id: nanoid(), name: "Gnocchi", description: "Soft potato dumplings served with sauce." },
        { id: nanoid(), name: "Bruschetta", description: "Toasted bread with tomatoes, garlic, and olive oil." },
        { id: nanoid(), name: "Minestrone Soup", description: "Vegetable soup with pasta or rice." },
        { id: nanoid(), name: "Cannoli", description: "Sicilian pastry filled with sweet ricotta cheese." },
        { id: nanoid(), name: "Pesto Pasta", description: "Pasta with basil, garlic, pine nuts, and parmesan." },
        { id: nanoid(), name: "Ravioli", description: "Stuffed pasta with various fillings." },
        { id: nanoid(), name: "Veal Saltimbocca", description: "Veal cutlets with prosciutto and sage." },
        { id: nanoid(), name: "Calzone", description: "Folded pizza with various fillings." },
        { id: nanoid(), name: "Cacio e Pepe", description: "Pasta with pecorino cheese and black pepper." },
        { id: nanoid(), name: "Panettone", description: "Italian Christmas bread with candied fruit." },
        { id: nanoid(), name: "Cioppino", description: "Italian-American seafood stew." },
        { id: nanoid(), name: "Eggplant Parmesan", description: "Breaded and fried eggplant with cheese and tomato sauce." },
        { id: nanoid(), name: "Focaccia", description: "Flat oven-baked bread with olive oil and herbs." },
        { id: nanoid(), name: "Zuppa Toscana", description: "Tuscan soup with sausage, kale, and potatoes." },
        { id: nanoid(), name: "Cappuccino", description: "Espresso coffee with frothy milk." },
        { id: nanoid(), name: "Torta della Nonna", description: "Grandmother's cake with custard and pine nuts." },
        { id: nanoid(), name: "Amatriciana", description: "Pasta with tomato sauce, guanciale, and pecorino cheese." },
        { id: nanoid(), name: "Bresaola", description: "Cured beef served with arugula and parmesan." },
        { id: nanoid(), name: "Linguine alle Vongole", description: "Linguine pasta with clams and white wine sauce." },
        { id: nanoid(), name: "Panna Cotta", description: "Creamy Italian dessert." },
        { id: nanoid(), name: "Stracciatella Gelato", description: "Creamy Italian ice cream with chocolate chips." },
        { id: nanoid(), name: "Caponata", description: "Sicilian eggplant dish with vegetables and sweet and sour sauce." },
    ],
    Mexican: [
        { id: nanoid(), name: "Tacos al Pastor", description: "Tacos with marinated pork, pineapple, and cilantro." },
        { id: nanoid(), name: "Chiles Rellenos", description: "Stuffed poblano peppers with cheese or meat." },
        { id: nanoid(), name: "Enchiladas Verdes", description: "Chicken enchiladas with green sauce." },
        { id: nanoid(), name: "Guacamole", description: "Avocado dip with tomatoes, onions, and lime." },
        { id: nanoid(), name: "Mole Poblano", description: "Rich, dark sauce served with chicken." },
        { id: nanoid(), name: "Ceviche", description: "Citrus-marinated seafood salad." },
        { id: nanoid(), name: "Pozole", description: "Hominy soup with meat and chili." },
        { id: nanoid(), name: "Tamales", description: "Steamed corn masa filled with various fillings." },
        { id: nanoid(), name: "Sopes", description: "Thick corn tortillas topped with beans, meat, and salsa." },
        { id: nanoid(), name: "Churros", description: "Fried dough pastry often served with chocolate dipping sauce." },
        { id: nanoid(), name: "Birria", description: "Spicy stew made with goat or beef." },
        { id: nanoid(), name: "Huevos Rancheros", description: "Fried eggs with salsa served on tortillas." },
        { id: nanoid(), name: "Quesadillas", description: "Folded tortillas filled with cheese and other ingredients." },
        { id: nanoid(), name: "Pambazo", description: "Sandwich made with a special bread roll dipped in red sauce." },
        { id: nanoid(), name: "Salsa Verde", description: "Green chili sauce used as a condiment." },
        { id: nanoid(), name: "Barbacoa", description: "Slow-cooked, seasoned meat, often wrapped in banana leaves." },
        { id: nanoid(), name: "Cochinita Pibil", description: "Marinated, slow-roasted pork dish." },
        { id: nanoid(), name: "Tostadas", description: "Crispy tortillas with various toppings." },
        { id: nanoid(), name: "Menudo", description: "Traditional Mexican soup with tripe and hominy." },
        { id: nanoid(), name: "Pepian", description: "Guatemalan stew with meat, vegetables, and spices." },
        { id: nanoid(), name: "Tlacoyos", description: "Stuffed, oval-shaped masa cakes." },
        { id: nanoid(), name: "Sopapillas", description: "Fried pastry dough served with honey or sugar." },
        { id: nanoid(), name: "Machaca", description: "Dried and shredded meat often used in burritos." },
        { id: nanoid(), name: "Chapulines", description: "Fried grasshoppers, a traditional snack in some regions." },
        { id: nanoid(), name: "Champurrado", description: "Thick, chocolate-based atole drink." },
        { id: nanoid(), name: "Molletes", description: "Open-faced sandwiches with refried beans and cheese." },
        { id: nanoid(), name: "Tlayudas", description: "Large, thin tortillas topped with various ingredients." },
        { id: nanoid(), name: "Camarones a la Diabla", description: "Spicy shrimp dish." },
        { id: nanoid(), name: "Salsa Roja", description: "Red chili sauce used as a condiment." },
        { id: nanoid(), name: "Tacos de Lengua", description: "Tacos filled with beef tongue." },
        { id: nanoid(), name: "Chicharrón en Salsa Verde", description: "Crispy pork skin in green sauce." },
        { id: nanoid(), name: "Tacos de Suadero", description: "Tacos filled with thin-cut beef." },
        { id: nanoid(), name: "Tacos de Cabeza", description: "Tacos filled with beef head meat." },
        { id: nanoid(), name: "Tacos de Camarón", description: "Shrimp tacos." },
        { id: nanoid(), name: "Pulpo a la Gallega", description: "Galician-style octopus dish." },
        { id: nanoid(), name: "Elote", description: "Grilled corn on the cob with various toppings." },
        { id: nanoid(), name: "Champurrado", description: "A thick, warm chocolate drink often served with churros." },
    ],
    Greek: [
        { id: nanoid(), name: "Moussaka", description: "Layered dish with eggplant, ground meat, and béchamel sauce." },
        { id: nanoid(), name: "Souvlaki", description: "Grilled skewers of meat, often served with pita and tzatziki." },
        { id: nanoid(), name: "Dolmas", description: "Grape leaves stuffed with rice and herbs." },
        { id: nanoid(), name: "Tzatziki", description: "Yogurt and cucumber dip with garlic and dill." },
        { id: nanoid(), name: "Spanakopita", description: "Spinach and feta cheese pie wrapped in filo pastry." },
        { id: nanoid(), name: "Kleftiko", description: "Slow-cooked lamb with garlic and lemon." },
        { id: nanoid(), name: "Saganaki", description: "Fried cheese served with lemon." },
        { id: nanoid(), name: "Pastitsio", description: "Baked pasta dish with layers of meat and béchamel sauce." },
        { id: nanoid(), name: "Avgolemono Soup", description: "Lemon and egg soup often with chicken and rice." },
        { id: nanoid(), name: "Loukoumades", description: "Greek honey and cinnamon doughnuts." },
        { id: nanoid(), name: "Horta", description: "Boiled wild greens with olive oil and lemon." },
        { id: nanoid(), name: "Keftedes", description: "Greek meatballs with herbs and spices." },
        { id: nanoid(), name: "Kataifi", description: "Dessert made of shredded filo dough with nuts and honey." },
        { id: nanoid(), name: "Galaktoboureko", description: "Semolina custard dessert wrapped in filo pastry." },
        { id: nanoid(), name: "Gemista", description: "Stuffed vegetables with rice and herbs." },
        { id: nanoid(), name: "Melitzanosalata", description: "Eggplant dip with garlic, olive oil, and lemon." },
        { id: nanoid(), name: "Kolokythokeftedes", description: "Zucchini fritters with herbs and cheese." },
        { id: nanoid(), name: "Yemista", description: "Baked stuffed tomatoes or peppers." },
        { id: nanoid(), name: "Baklava", description: "Sweet pastry made of layers of filo dough, nuts, and syrup." },
        { id: nanoid(), name: "Retsina", description: "Greek white wine with a unique pine resin flavor." },
        { id: nanoid(), name: "Psarosoupa", description: "Greek fish soup with vegetables and herbs." },
        { id: nanoid(), name: "Kolokithopita", description: "Zucchini and feta cheese pie wrapped in filo pastry." },
        { id: nanoid(), name: "Kalamari Tiganito", description: "Fried calamari rings." },
        { id: nanoid(), name: "Paximadia", description: "Greek biscotti made with dried fruits and nuts." },
        { id: nanoid(), name: "Revani", description: "Syrup-soaked semolina cake." },
        { id: nanoid(), name: "Kokoretsi", description: "Grilled offal skewers wrapped in intestines." },
        { id: nanoid(), name: "Taramosalata", description: "Fish roe dip with lemon and olive oil." },
        { id: nanoid(), name: "Kreatopita", description: "Greek meat pie with minced meat and filo pastry." },
        { id: nanoid(), name: "Lahanodolmades", description: "Cabbage rolls stuffed with rice and meat." },
        { id: nanoid(), name: "Koupes", description: "Bulgur and meat croquettes." },
        { id: nanoid(), name: "Fasolada", description: "Greek bean soup with vegetables and herbs." },
    ],
        Moroccan: [
            { id: nanoid(), name: "Tagine", description: "Slow-cooked stew with meat, vegetables, and spices." },
            { id: nanoid(), name: "Couscous", description: "Steamed semolina grains often served with stew." },
            { id: nanoid(), name: "Harira", description: "Tomato and lentil soup, often enjoyed during Ramadan." },
            { id: nanoid(), name: "Bastilla", description: "Sweet and savory pie with layers of pastry, meat, and almonds." },
            { id: nanoid(), name: "Kefta Tagine", description: "Tagine with seasoned meatballs, tomatoes, and eggs." },
            { id: nanoid(), name: "Mechoui", description: "Whole roasted lamb or sheep, often served at celebrations." },
            { id: nanoid(), name: "Zaalouk", description: "Eggplant and tomato salad with spices and olive oil." },
            { id: nanoid(), name: "Mrouzia", description: "Sweet and savory lamb or beef stew with honey and spices." },
            { id: nanoid(), name: "Pastilla", description: "Flaky pastry filled with pigeon or chicken, almonds, and spices." },
            { id: nanoid(), name: "Tanjiya", description: "Clay pot dish with meat, preserved lemon, and spices." },
            { id: nanoid(), name: "Chermoula", description: "Herb and spice marinade used for grilling or roasting." },
            { id: nanoid(), name: "Briouats", description: "Stuffed pastry triangles with various fillings." },
            { id: nanoid(), name: "Maakouda", description: "Fried potato cakes often served in sandwiches." },
            { id: nanoid(), name: "Rfissa", description: "Chicken stew with lentils and shredded msemen bread." },
            { id: nanoid(), name: "Harcha", description: "Semolina flatbread often served with honey or cheese." },
            { id: nanoid(), name: "Khobz", description: "Traditional Moroccan bread." },
            { id: nanoid(), name: "Chebakia", description: "Honey and sesame cookies, often served during Ramadan." },
            { id: nanoid(), name: "Seffa Medfouna", description: "Sweet couscous with cinnamon, almonds, and raisins." },
            { id: nanoid(), name: "Sardines en Chermoula", description: "Grilled sardines with herb and spice sauce." },
            { id: nanoid(), name: "Tangia", description: "Slow-cooked beef dish with preserved lemon and spices." },
            { id: nanoid(), name: "Sellou", description: "Sweet Moroccan energy balls made with almonds and sesame seeds." },
            { id: nanoid(), name: "Rghaif", description: "Layered flatbread often filled with cheese or meat." },
            { id: nanoid(), name: "Makrout", description: "Date-filled semolina pastry often fried or baked." },
            { id: nanoid(), name: "Bissara", description: "Fava bean soup with garlic and spices." },
            { id: nanoid(), name: "Mesfouf", description: "Steamed couscous salad with almonds and raisins." },
            { id: nanoid(), name: "Loubia", description: "White bean stew with tomatoes and spices." },
            { id: nanoid(), name: "Tajine El Bey", description: "Lamb and vegetable tagine with almonds and eggs." },
            { id: nanoid(), name: "Zitouna", description: "Olives, often served as an appetizer." },
            { id: nanoid(), name: "Makrout el Louse", description: "Almond and sesame-filled pastries." },
            { id: nanoid(), name: "Berkoukes", description: "Large pasta pearls served in a flavorful broth." },
            { id: nanoid(), name: "M'rouzia", description: "Lamb or beef stew with honey and spices." },
        ],
        French: [
            { id: nanoid(), name: "Coq au Vin", description: "Chicken cooked in red wine with mushrooms and onions." },
            { id: nanoid(), name: "Bouillabaisse", description: "Fish stew with various seafood and herbs." },
            { id: nanoid(), name: "Croissant", description: "Flaky and buttery pastry often enjoyed for breakfast." },
            { id: nanoid(), name: "Quiche Lorraine", description: "Savory tart with bacon and cheese." },
            { id: nanoid(), name: "Escargot", description: "Snails cooked in garlic and herb butter." },
            { id: nanoid(), name: "Ratatouille", description: "Provençal vegetable stew." },
            { id: nanoid(), name: "Cassoulet", description: "Slow-cooked casserole with meat and white beans." },
            { id: nanoid(), name: "Foie Gras", description: "Duck or goose liver pâté." },
            { id: nanoid(), name: "Crème Brûlée", description: "Creamy custard dessert with a caramelized sugar topping." },
            { id: nanoid(), name: "Beef Bourguignon", description: "Beef stew with red wine, onions, and mushrooms." },
            { id: nanoid(), name: "Salade Niçoise", description: "Salad with tuna, olives, eggs, and vegetables." },
            { id: nanoid(), name: "Duck à l'Orange", description: "Duck with sweet orange sauce." },
            { id: nanoid(), name: "Tarte Tatin", description: "Upside-down caramelized apple tart." },
            { id: nanoid(), name: "Coquilles Saint-Jacques", description: "Scallops in a creamy sauce, often served in a shell." },
            { id: nanoid(), name: "Boeuf en Croute", description: "Beef Wellington with pastry crust." },
            { id: nanoid(), name: "French Onion Soup", description: "Onion soup with melted cheese on top." },
            { id: nanoid(), name: "Sole Meunière", description: "Pan-fried sole fish with brown butter and lemon." },
            { id: nanoid(), name: "Boudin Noir", description: "Blood sausage." },
            { id: nanoid(), name: "Pot-au-Feu", description: "French beef stew." },
            { id: nanoid(), name: "Pissaladière", description: "Provençal tart with caramelized onions, anchovies, and olives." },
            { id: nanoid(), name: "Cassoulet", description: "Slow-cooked casserole with meat and white beans." },
            { id: nanoid(), name: "Macarons", description: "Colorful almond meringue cookies filled with ganache." },
            { id: nanoid(), name: "Tarte Flambée", description: "Thin, crispy pizza-like tart with cream, onions, and bacon." },
            { id: nanoid(), name: "Poulet à la Moutarde", description: "Chicken in creamy mustard sauce." },
            { id: nanoid(), name: "Chateaubriand", description: "Thick steak filet often served with béarnaise sauce." },
            { id: nanoid(), name: "Crêpes", description: "Thin pancakes often served with various fillings." },
            { id: nanoid(), name: "Cassoulet", description: "Slow-cooked casserole with meat and white beans." },
            { id: nanoid(), name: "Piperade", description: "Basque dish with peppers, onions, and tomatoes." },
            { id: nanoid(), name: "Mille-Feuille", description: "Layered pastry dessert with cream and icing." },
            { id: nanoid(), name: "Pommes Anna", description: "Sliced and layered potatoes cooked with butter." },
            { id: nanoid(), name: "Gratin Dauphinois", description: "Potato gratin with cream, garlic, and cheese." },
        ],
        Spanish: [
            { id: nanoid(), name: "Paella", description: "Saffron-infused rice dish with seafood or meat." },
            { id: nanoid(), name: "Gazpacho", description: "Cold tomato soup with vegetables and olive oil." },
            { id: nanoid(), name: "Churros", description: "Fried dough pastry often served with chocolate dipping sauce." },
            { id: nanoid(), name: "Tortilla Española", description: "Spanish omelette with potatoes and onions." },
            { id: nanoid(), name: "Pulpo a la Gallega", description: "Galician-style octopus dish." },
            { id: nanoid(), name: "Jamon Ibérico", description: "Cured ham from Iberian pigs." },
            { id: nanoid(), name: "Patatas Bravas", description: "Fried potatoes served with spicy tomato sauce." },
            { id: nanoid(), name: "Crema Catalana", description: "Catalan dessert similar to crème brûlée." },
            { id: nanoid(), name: "Sangria", description: "Spanish wine punch with fruit." },
            { id: nanoid(), name: "Pinchos", description: "Skewered tapas often with various toppings." },
            { id: nanoid(), name: "Fabada Asturiana", description: "Asturian bean stew with sausage and ham." },
            { id: nanoid(), name: "Bocadillo de Jamón", description: "Spanish ham sandwich." },
            { id: nanoid(), name: "Salmorejo", description: "Creamy tomato and bread soup, similar to gazpacho." },
            { id: nanoid(), name: "Turron", description: "Spanish nougat often enjoyed during Christmas." },
            { id: nanoid(), name: "Pisto", description: "Spanish ratatouille with tomatoes, peppers, and zucchini." },
            { id: nanoid(), name: "Gambas al Ajillo", description: "Garlic shrimp sautéed in olive oil." },
            { id: nanoid(), name: "Rabo de Toro", description: "Braised oxtail stew." },
            { id: nanoid(), name: "Flan", description: "Caramel custard dessert." },
            { id: nanoid(), name: "Migas", description: "Crumbs fried with garlic, paprika, and sausage." },
            { id: nanoid(), name: "Albóndigas", description: "Spanish meatballs often served in a tomato sauce." },
            { id: nanoid(), name: "Tarta de Santiago", description: "Spanish almond cake with powdered sugar cross." },
            { id: nanoid(), name: "Calamares a la Romana", description: "Fried squid rings in a light batter." },
            { id: nanoid(), name: "Empanadas", description: "Pastry turnovers filled with various ingredients." },
            { id: nanoid(), name: "Caracoles a la Madrileña", description: "Madrid-style snails with tomato and herbs." },
            { id: nanoid(), name: "Horchata de Chufa", description: "Sweet, milky drink made from tiger nuts." },
            { id: nanoid(), name: "Tarta de Queso", description: "Spanish cheesecake often with a caramelized top." },
            { id: nanoid(), name: "Pimientos de Padrón", description: "Blistered green peppers with sea salt." },
            { id: nanoid(), name: "Cocido Madrileño", description: "Madrid-style chickpea stew with various meats." },
            { id: nanoid(), name: "Txistorra", description: "Basque thin sausage often grilled or fried." },
            { id: nanoid(), name: "Arroz Negro", description: "Black rice dish made with squid ink." },
            { id: nanoid(), name: "Criadillas", description: "Bull's testicles, a delicacy in some regions." },
            { id: nanoid(), name: "Pisto Manchego", description: "Castilian ratatouille with tomatoes, peppers, and eggs." },
            { id: nanoid(), name: "Tarta de Manzana", description: "Spanish apple cake often served with cream." },
            { id: nanoid(), name: "Guisantes con Jamón", description: "Peas with ham, often served as a side dish." },
            { id: nanoid(), name: "Morcilla", description: "Spanish blood sausage." },
        ],
            Korean: [
                { id: nanoid(), name: "Bulgogi", description: "Marinated and grilled beef or pork." },
                { id: nanoid(), name: "Kimchi", description: "Fermented cabbage and vegetables with spicy seasonings." },
                { id: nanoid(), name: "Bibimbap", description: "Rice dish with vegetables, meat, and a spicy sauce." },
                { id: nanoid(), name: "Japchae", description: "Stir-fried glass noodles with vegetables and meat." },
                { id: nanoid(), name: "Dak Galbi", description: "Spicy stir-fried chicken with vegetables." },
                { id: nanoid(), name: "Samgyeopsal", description: "Grilled pork belly often wrapped in lettuce." },
                { id: nanoid(), name: "Tteokbokki", description: "Spicy rice cakes with gochujang sauce." },
                { id: nanoid(), name: "Haemul Pajeon", description: "Seafood and scallion pancake." },
                { id: nanoid(), name: "Galbitang", description: "Clear beef short rib soup." },
                { id: nanoid(), name: "Kimbap", description: "Korean rice rolls with various fillings." },
                { id: nanoid(), name: "Sundubu Jjigae", description: "Soft tofu stew with vegetables and meat or seafood." },
                { id: nanoid(), name: "Dolsot Bibimbap", description: "Bibimbap served in a hot stone pot." },
                { id: nanoid(), name: "Yukgaejang", description: "Spicy beef soup with vegetables and noodles." },
                { id: nanoid(), name: "Jajangmyeon", description: "Noodles with black bean sauce." },
                { id: nanoid(), name: "Ojingeo Bokkeum", description: "Spicy stir-fried squid." },
                { id: nanoid(), name: "Kimchi Jjigae", description: "Kimchi stew with tofu and pork." },
                { id: nanoid(), name: "Bulgogi", description: "Marinated and grilled beef or pork." },
                { id: nanoid(), name: "Korean Fried Chicken", description: "Crispy fried chicken with spicy or sweet sauce." },
                { id: nanoid(), name: "Bibim Naengmyeon", description: "Cold noodles with spicy sauce and vegetables." },
                { id: nanoid(), name: "Jokbal", description: "Braised pig's trotters." },
                { id: nanoid(), name: "Odeng", description: "Fish cake skewers often served in broth." },
                { id: nanoid(), name: "Bungeoppang", description: "Fish-shaped pastry filled with sweet red bean paste." },
                { id: nanoid(), name: "Gimbap", description: "Korean seaweed rice rolls with various fillings." },
                { id: nanoid(), name: "Kongguksu", description: "Cold soybean noodle soup." },
                { id: nanoid(), name: "Gyeran Jjim", description: "Steamed egg custard." },
                { id: nanoid(), name: "Makgeolli", description: "Korean rice wine." },
                { id: nanoid(), name: "Dak Bulgogi", description: "Marinated and grilled chicken." },
                { id: nanoid(), name: "Kkakdugi", description: "Cubed radish kimchi." },
                { id: nanoid(), name: "Ganjang Gejang", description: "Raw marinated crab." },
                { id: nanoid(), name: "Mul Naengmyeon", description: "Cold noodles in a beef broth." },
                { id: nanoid(), name: "Bindaetteok", description: "Mung bean pancake." },
            ],
            Brazilian: [
                { id: nanoid(), name: "Feijoada", description: "Black bean stew with pork and sausage." },
                { id: nanoid(), name: "Pão de Queijo", description: "Cheese bread rolls, a popular snack." },
                { id: nanoid(), name: "Churrasco", description: "Brazilian barbecue with various meats." },
                { id: nanoid(), name: "Coxinha", description: "Deep-fried chicken croquettes." },
                { id: nanoid(), name: "Moqueca", description: "Fish stew with coconut milk and palm oil." },
                { id: nanoid(), name: "Açaí Bowl", description: "Smoothie bowl made with açaí berries and toppings." },
                { id: nanoid(), name: "Pastel", description: "Deep-fried pastry filled with various ingredients." },
                { id: nanoid(), name: "Brigadeiro", description: "Chocolate truffle-like dessert." },
                { id: nanoid(), name: "Empada", description: "Savory pastry filled with meat or cheese." },
                { id: nanoid(), name: "Acarajé", description: "Deep-fried black-eyed pea fritters, often stuffed." },
                { id: nanoid(), name: "Tapioca", description: "Cassava flour crepe filled with various fillings." },
                { id: nanoid(), name: "Baião de Dois", description: "Rice and black-eyed pea dish with sausage." },
                { id: nanoid(), name: "Picanha", description: "Prime beef cut often grilled." },
                { id: nanoid(), name: "Quindim", description: "Custard dessert made with egg yolks." },
                { id: nanoid(), name: "Carne de Sol", description: "Sun-dried and salted beef, often grilled." },
                { id: nanoid(), name: "Cuscuz Nordestino", description: "Steamed cornmeal dish, popular in the Northeast." },
                { id: nanoid(), name: "Vatapá", description: "Spicy shrimp and bread stew with coconut milk." },
                { id: nanoid(), name: "Xinxim de Galinha", description: "Chicken stew with peanuts and spices." },
                { id: nanoid(), name: "Bolo de Rolo", description: "Swiss roll cake filled with guava paste." },
                { id: nanoid(), name: "Farofa", description: "Toasted cassava flour often served as a side dish." },
                { id: nanoid(), name: "Canjica", description: "Sweet hominy porridge often enjoyed during festivals." },
                { id: nanoid(), name: "Tutu de Feijão", description: "Mashed beans dish with spices and sausage." },
                { id: nanoid(), name: "Coxa Creme", description: "Chicken drumsticks in a creamy sauce." },
                { id: nanoid(), name: "Tacacá", description: "Amazonian soup with tapioca pearls and shrimp." },
                { id: nanoid(), name: "Frango à Passarinho", description: "Fried chicken bites often seasoned with garlic and lime." },
                { id: nanoid(), name: "Buchada de Bode", description: "Goat stomach stuffed with spices and herbs." },
                { id: nanoid(), name: "Canjiquinha", description: "Hominy corn porridge with sausage and vegetables." },
                { id: nanoid(), name: "Bolo de Milho", description: "Corn cake often served as a dessert." },
                { id: nanoid(), name: "Arroz Carreteiro", description: "Rice dish with dried meat and spices." },
                { id: nanoid(), name: "Sorvete de Açaí", description: "Açaí berry ice cream." },
            ],
            Lebanese: [
                { id: nanoid(), name: "Hummus", description: "Chickpea dip with tahini, lemon, and garlic." },
                { id: nanoid(), name: "Falafel", description: "Deep-fried chickpea or fava bean patties." },
                { id: nanoid(), name: "Tabbouleh", description: "Salad made with bulgur wheat, parsley, and tomatoes." },
                { id: nanoid(), name: "Kebbeh", description: "Bulgur and minced meat dish, often fried or baked." },
                { id: nanoid(), name: "Baba Ghanoush", description: "Smoky eggplant dip with tahini and garlic." },
                { id: nanoid(), name: "Fattoush", description: "Salad with toasted bread, vegetables, and sumac." },
                { id: nanoid(), name: "Shawarma", description: "Sliced meat (usually lamb or chicken) in flatbread." },
                { id: nanoid(), name: "Manousheh", description: "Lebanese flatbread often topped with za'atar." },
                { id: nanoid(), name: "Kafta", description: "Grilled or skewered minced meat with spices." },
                { id: nanoid(), name: "Moussaka", description: "Eggplant casserole with minced meat and tomatoes." },
                { id: nanoid(), name: "Lentil Soup", description: "Spiced soup made with lentils." },
                { id: nanoid(), name: "Sambousek", description: "Pastry filled with minced meat, cheese, or spinach." },
                { id: nanoid(), name: "Labneh", description: "Strained yogurt often served with olive oil and herbs." },
                { id: nanoid(), name: "Ful Medames", description: "Fava bean stew with olive oil and spices." },
                { id: nanoid(), name: "Stuffed Grape Leaves", description: "Grape leaves filled with rice and herbs." },
                { id: nanoid(), name: "Makloubeh", description: "Upside-down rice and vegetable dish." },
                { id: nanoid(), name: "Lahmacun", description: "Flatbread with minced meat, vegetables, and spices." },
                { id: nanoid(), name: "Sfiha", description: "Lebanese meat pies with minced meat and spices." },
                { id: nanoid(), name: "Knafeh", description: "Sweet pastry made with shredded phyllo dough, cheese, and syrup." },
                { id: nanoid(), name: "Jawaneh", description: "Grilled chicken wings with garlic and lemon." },
                { id: nanoid(), name: "Mhammara", description: "Spicy red pepper and walnut dip." },
                { id: nanoid(), name: "Roz Bel Laban", description: "Rice pudding dessert with rosewater." },
                { id: nanoid(), name: "Mujadara", description: "Lentils and rice dish with caramelized onions." },
                { id: nanoid(), name: "Shanklish", description: "Aged cheese balls coated with spices." },
                { id: nanoid(), name: "Fasolia", description: "Green bean stew with tomatoes and spices." },
                { id: nanoid(), name: "Hrisseh", description: "Wheat and meat porridge, often eaten on special occasions." },
                { id: nanoid(), name: "Batata Harra", description: "Spicy roasted potatoes with garlic and coriander." },
                { id: nanoid(), name: "Kousa Mahshi", description: "Stuffed zucchini with minced meat and rice." },
                { id: nanoid(), name: "Kebbeh Nayyeh", description: "Raw minced meat dish with bulgur and spices." },
                { id: nanoid(), name: "Moussaka", description: "Eggplant casserole with minced meat and tomatoes." },
            ],
            Vietnamese: [
                { id: nanoid(), name: "Pho", description: "Noodle soup with beef or chicken, herbs, and rice noodles." },
                { id: nanoid(), name: "Banh Mi", description: "Vietnamese sandwich with various fillings." },
                { id: nanoid(), name: "Goi Cuon", description: "Fresh spring rolls with shrimp, herbs, and rice vermicelli." },
                { id: nanoid(), name: "Bun Cha", description: "Grilled pork and vermicelli noodle dish." },
                { id: nanoid(), name: "Com Ga Hoi An", description: "Hoi An-style chicken rice." },
                { id: nanoid(), name: "Cao Lau", description: "Regional noodle dish with pork and herbs." },
                { id: nanoid(), name: "Bun Bo Hue", description: "Spicy beef noodle soup from Hue." },
                { id: nanoid(), name: "Bun Rieu Cua", description: "Crab noodle soup." },
                { id: nanoid(), name: "Ca Kho To", description: "Caramelized fish in clay pot." },
                { id: nanoid(), name: "Cha Ca Thang Long", description: "Turmeric-marinated fish with herbs and vermicelli." },
                { id: nanoid(), name: "Goi Du Du Kho Bo", description: "Green papaya salad with beef jerky." },
                { id: nanoid(), name: "Banh Xeo", description: "Crispy rice flour pancake with fillings." },
                { id: nanoid(), name: "Canh Chua", description: "Sour soup with fish and vegetables." },
                { id: nanoid(), name: "Bo Luc Lac", description: "Shaking beef with garlic and soy sauce." },
                { id: nanoid(), name: "Hu Tieu", description: "Clear noodle soup with various proteins." },
                { id: nanoid(), name: "Goi Ga Bap Cai", description: "Cabbage and chicken salad." },
                { id: nanoid(), name: "Bun Thit Nuong", description: "Grilled pork and vermicelli noodle dish." },
                { id: nanoid(), name: "Banh Canh Cua", description: "Thick crab soup with tapioca noodles." },
                { id: nanoid(), name: "Nom Hoa Chuoi", description: "Banana blossom salad with pork and shrimp." },
                { id: nanoid(), name: "Banh Khoai", description: "Savory rice pancake with shrimp and herbs." },
                { id: nanoid(), name: "Bun Oc", description: "Snail noodle soup." },
                { id: nanoid(), name: "Banh Bot Loc", description: "Tapioca dumplings with shrimp and pork." },
                { id: nanoid(), name: "Ca Ri Ga", description: "Chicken curry with baguette or rice." },
                { id: nanoid(), name: "Bun Thang", description: "Hanoi-style vermicelli noodle soup." },
                { id: nanoid(), name: "Bun Mang Vit", description: "Bamboo shoot and duck noodle soup." },
                { id: nanoid(), name: "Banh Chung", description: "Sticky rice cake filled with mung bean and pork." },
                { id: nanoid(), name: "Bun Bo Nam Bo", description: "Noodle bowl with beef, herbs, and peanuts." },
                { id: nanoid(), name: "Bun Mam", description: "Fermented fish noodle soup." },
                { id: nanoid(), name: "Che", description: "Vietnamese sweet dessert soup." },
                { id: nanoid(), name: "Banh It Tran", description: "Steamed glutinous rice cakes with shrimp." },
                { id: nanoid(), name: "Banh Cuon", description: "Steamed rice rolls filled with minced pork and mushrooms." },
            ],
            Jamaican: [
                { id: nanoid(), name: "Jerk Chicken", description: "Chicken marinated in jerk spice and grilled." },
                { id: nanoid(), name: "Curry Goat", description: "Goat meat stewed in a rich curry sauce." },
                { id: nanoid(), name: "Ackee and Saltfish", description: "National dish made with ackee fruit and salted codfish." },
                { id: nanoid(), name: "Escovitch Fish", description: "Fried fish with pickled vegetables and spicy sauce." },
                { id: nanoid(), name: "Oxtail Stew", description: "Stew made with oxtail, butter beans, and spices." },
                { id: nanoid(), name: "Jamaican Patty", description: "Spiced meat-filled pastry." },
                { id: nanoid(), name: "Bammy", description: "Cassava flatbread often served with fish." },
                { id: nanoid(), name: "Run Down", description: "Fish stew with coconut milk and spices." },
                { id: nanoid(), name: "Callaloo", description: "Leafy green vegetable stew." },
                { id: nanoid(), name: "Rice and Peas", description: "Coconut rice with kidney beans." },
                { id: nanoid(), name: "Gizzada", description: "Coconut pastry with sweet and spicy filling." },
                { id: nanoid(), name: "Mannish Water", description: "Spicy goat head soup." },
                { id: nanoid(), name: "Roast Breadfruit", description: "Roasted breadfruit often served as a side dish." },
                { id: nanoid(), name: "Jamaican Sorrel Drink", description: "Refreshing hibiscus drink." },
                { id: nanoid(), name: "Jamaican Pepperpot Soup", description: "Spicy soup with vegetables and meat." },
                { id: nanoid(), name: "Festival", description: "Sweet cornmeal dumplings." },
                { id: nanoid(), name: "Bulla Cake", description: "Spiced molasses and ginger cake." },
                { id: nanoid(), name: "Solomon Gundy", description: "Spicy pickled herring spread." },
                { id: nanoid(), name: "Coconut Drops", description: "Coconut candy with spices and ginger." },
                { id: nanoid(), name: "Jamaican Sweet Potato Pudding", description: "Dessert made with sweet potato and coconut." },
                { id: nanoid(), name: "Blue Drawers", description: "Sweet potato and coconut pudding wrapped in banana leaves." },
                { id: nanoid(), name: "Toto", description: "Coconut cake with spices." },
                { id: nanoid(), name: "Corned Pork", description: "Salted and spiced pork." },
                { id: nanoid(), name: "Bamboo Shoot Soup", description: "Soup made with bamboo shoots and spices." },
                { id: nanoid(), name: "Jamaican Easter Bun", description: "Fruitcake-like bun often eaten at Easter." },
                { id: nanoid(), name: "Jamaican Black Cake", description: "Rich fruitcake soaked in rum." },
                { id: nanoid(), name: "Guava Duff", description: "Steamed dessert with guava filling." },
                { id: nanoid(), name: "Jamaican Grater Cake", description: "Grated coconut and sugar cake." },
                { id: nanoid(), name: "Jamaican Christmas Cake", description: "Fruitcake enjoyed during the holidays." },
                { id: nanoid(), name: "Jamaican Tamarind Balls", description: "Tamarind fruit and sugar candy." },
            ],
            Turkish: [
                { id: nanoid(), name: "Kebab", description: "Various grilled meat dishes, such as Adana and Iskender kebabs." },
                { id: nanoid(), name: "Baklava", description: "Sweet pastry made of layers of filo dough, filled with nuts and honey." },
                { id: nanoid(), name: "Manti", description: "Turkish dumplings filled with minced meat or lentils, often served with yogurt and garlic sauce." },
                { id: nanoid(), name: "Lahmacun", description: "Thin, round flatbread topped with minced meat, vegetables, and herbs." },
                { id: nanoid(), name: "Simit", description: "Circular bread encrusted with sesame seeds, often enjoyed as a snack." },
                { id: nanoid(), name: "Dolma", description: "Stuffed vegetables or vine leaves, commonly with rice and herbs." },
                { id: nanoid(), name: "Menemen", description: "Scrambled eggs with tomatoes, green peppers, and spices." },
                { id: nanoid(), name: "Pide", description: "Turkish pizza-like flatbread often topped with cheese, meat, and vegetables." },
                { id: nanoid(), name: "Pilav", description: "Turkish rice dish often cooked with vermicelli or other grains." },
                { id: nanoid(), name: "Kumpir", description: "Baked potato dish often stuffed with various toppings." },
                { id: nanoid(), name: "Cacik", description: "Yogurt and cucumber dip with garlic and herbs." },
                { id: nanoid(), name: "Kofte", description: "Minced meat patties, typically made from beef or lamb." },
                { id: nanoid(), name: "Turkish Delight (Lokum)", description: "Chewy, sweet confection often flavored with rosewater or fruit." },
                { id: nanoid(), name: "Piyaz", description: "White bean salad with onions, tomatoes, and parsley." },
                { id: nanoid(), name: "Doner Kebab", description: "Rotating skewer of seasoned meat slices, often served in a sandwich." },
                { id: nanoid(), name: "Muhlama", description: "Creamy cornmeal porridge with cheese, also known as 'Turkish fondue'." },
                { id: nanoid(), name: "Kuzu Tandir", description: "Slow-cooked lamb or mutton, often served with rice or bread." },
                { id: nanoid(), name: "Ayran", description: "Yogurt-based beverage often served as a refreshing drink." },
                { id: nanoid(), name: "Kazandibi", description: "Caramelized milk pudding with a burnt top." },
                { id: nanoid(), name: "Cezerye", description: "Turkish sweet made with caramelized carrots, nuts, and coconut." },
                { id: nanoid(), name: "Karniyarik", description: "Stuffed eggplant with minced meat and vegetables." },
                { id: nanoid(), name: "Sarma", description: "Grape leaves or cabbage leaves stuffed with rice and meat." },
                { id: nanoid(), name: "Acik Ekmek", description: "Turkish open-faced sandwiches often topped with various ingredients." },
                { id: nanoid(), name: "Mastava", description: "Traditional Turkish yogurt soup." },
                { id: nanoid(), name: "Tavuk Pilav", description: "Chicken and rice dish, a popular street food." },
                { id: nanoid(), name: "Kemalpasa", description: "Syrup-soaked sponge cake often topped with pistachios." },
                { id: nanoid(), name: "Midye Dolma", description: "Stuffed mussels with a rice mixture." },
                { id: nanoid(), name: "Kuzu Incik", description: "Slow-cooked lamb shanks with vegetables and spices." },
                { id: nanoid(), name: "Ezogelin Soup", description: "Red lentil soup with bulgur, spices, and mint." },
                { id: nanoid(), name: "Cig Kofte", description: "Spicy bulgur and minced meat dish, often eaten as a snack." },
            ],
            Ethiopian: [
                { id: nanoid(), name: "Injera", description: "Spongy sourdough flatbread, a staple in Ethiopian cuisine." },
                { id: nanoid(), name: "Doro Wat", description: "Spicy chicken stew made with berbere spice and served with injera." },
                { id: nanoid(), name: "Kitfo", description: "Minced raw beef dish, often served with spices and injera." },
                { id: nanoid(), name: "Tibs", description: "Stir-fried meat or vegetables with spices." },
                { id: nanoid(), name: "Shiro", description: "Ground chickpea or lentil stew, a vegetarian favorite." },
                { id: nanoid(), name: "Teff", description: "Tiny grain used to make injera, porridge, and other dishes." },
                { id: nanoid(), name: "Kik Alicha", description: "Yellow split pea stew, a mild and vegetarian option." },
                { id: nanoid(), name: "Gomen Wat", description: "Collard greens stewed with spices." },
                { id: nanoid(), name: "Dulet", description: "Spicy minced organ meat dish, often eaten for breakfast." },
                { id: nanoid(), name: "Tire Siga", description: "Raw beef served as a tartare." },
                { id: nanoid(), name: "Dabo Kolo", description: "Small baked bread snacks, perfect for on-the-go." },
                { id: nanoid(), name: "Ayibe", description: "Mild cheese often served with Ethiopian dishes." },
                { id: nanoid(), name: "Yebeg Tibs", description: "Spicy grilled lamb or mutton." },
                { id: nanoid(), name: "Firfir", description: "Spicy shredded injera dish, often served for breakfast." },
                { id: nanoid(), name: "Ful", description: "Fava bean stew, a popular breakfast dish." },
                { id: nanoid(), name: "Kolo", description: "Toasted barley or chickpea snacks." },
                { id: nanoid(), name: "Genfo", description: "Porridge made from barley or wheat flour." },
                { id: nanoid(), name: "Gored Gored", description: "Rare beef cubes seasoned with spices." },
                { id: nanoid(), name: "Yetsom Beyaynetu", description: "Vegetarian platter with a variety of dishes." },
                { id: nanoid(), name: "Aysh", description: "Ethiopian porridge made from grains or legumes." },
                { id: nanoid(), name: "Tere Siga", description: "Spicy raw meat, similar to kitfo but with different spices." },
                { id: nanoid(), name: "Yekik Alicha", description: "Yellow split pea stew, a mild and vegetarian option." },
                { id: nanoid(), name: "Dabu", description: "Spiced roasted barley, often eaten as a snack." },
                { id: nanoid(), name: "Qolo", description: "Roasted barley or lentil stew." },
                { id: nanoid(), name: "Beso", description: "Roasted barley flour porridge." },
                { id: nanoid(), name: "Shorba", description: "Ethiopian soup often made with lentils." },
                { id: nanoid(), name: "Beyaynetu", description: "Vegetarian platter with a variety of dishes." },
                { id: nanoid(), name: "Fit-fit", description: "Dish made from shredded injera mixed with spices and vegetables." },
                { id: nanoid(), name: "Awaze Tibs", description: "Spicy beef or lamb dish often served with injera." },
                { id: nanoid(), name: "Dabo", description: "Ethiopian bread, similar to injera." },
                { id: nanoid(), name: "Tella", description: "Traditional Ethiopian beer." },
                { id: nanoid(), name: "Tej", description: "Honey wine, a popular Ethiopian alcoholic beverage." },
            ],
            Russian: [
                { id: nanoid(), name: "Borscht", description: "Beet soup often served with sour cream." },
                { id: nanoid(), name: "Pelmeni", description: "Dumplings typically filled with meat, served with sour cream." },
                { id: nanoid(), name: "Pirozhki", description: "Small savory pastries filled with various ingredients." },
                { id: nanoid(), name: "Beef Stroganoff", description: "Sautéed beef strips in a creamy sauce." },
                { id: nanoid(), name: "Olivier Salad", description: "Russian potato salad with vegetables and mayonnaise." },
                { id: nanoid(), name: "Solyanka", description: "Thick, sour soup with meat, vegetables, and pickles." },
                { id: nanoid(), name: "Blini", description: "Thin pancakes often served with sour cream, caviar, or jam." },
                { id: nanoid(), name: "Shashlik", description: "Marinated and grilled skewered meat, similar to kebabs." },
                { id: nanoid(), name: "Herring Under a Fur Coat", description: "Layered salad with herring, beets, potatoes, and mayo." },
                { id: nanoid(), name: "Kasha", description: "Porridge made from grains like buckwheat or oats." },
                { id: nanoid(), name: "Pirog", description: "Large savory or sweet pies with various fillings." },
                { id: nanoid(), name: "Kvass", description: "Fermented beverage made from bread, often served cold." },
                { id: nanoid(), name: "Syrniki", description: "Fried quark cheese pancakes, served with sour cream." },
                { id: nanoid(), name: "Holodets", description: "Jellied meat dish, often served cold." },
                { id: nanoid(), name: "Rassolnik", description: "Pickle soup with meat or fish." },
                { id: nanoid(), name: "Pryaniki", description: "Spiced honey cakes, a popular dessert." },
                { id: nanoid(), name: "Medovik", description: "Layered honey cake, often enjoyed during celebrations." },
                { id: nanoid(), name: "Kartoshka", description: "Chocolate-covered potato-shaped cake." },
                { id: nanoid(), name: "Kulebyaka", description: "Savory pie filled with fish, meat, or mushrooms." },
                { id: nanoid(), name: "Rye Bread", description: "Dark, dense bread often served with butter or cheese." },
                { id: nanoid(), name: "Uha", description: "Fish soup made with various freshwater fish." },
                { id: nanoid(), name: "Syrnaya Zapekanka", description: "Baked cottage cheese dessert." },
                { id: nanoid(), name: "Kotleti", description: "Russian-style meat patties." },
                { id: nanoid(), name: "Kavkazskaya Shaurma", description: "Caucasian-style shawarma with grilled meat and veggies." },
                { id: nanoid(), name: "Tula Gingerbread", description: "Spiced gingerbread cookies from Tula." },
                { id: nanoid(), name: "Salat Olivier", description: "A variation of Olivier salad with meat and vegetables." },
                { id: nanoid(), name: "Kisel", description: "Fruit jelly dessert." },
                { id: nanoid(), name: "Paskha", description: "Traditional Easter dessert made with quark cheese." },
                { id: nanoid(), name: "Golubtsy", description: "Cabbage rolls stuffed with meat and rice." },
                { id: nanoid(), name: "Pavlova", description: "Meringue-based dessert topped with fruit and cream." },
    ],
    AmericanIndian: [
                { id: nanoid(), name: "Frybread", description: "Deep-fried flatbread, often served with toppings like beans and cheese." },
                { id: nanoid(), name: "Bison Burger", description: "Burger made from lean bison meat." },
                { id: nanoid(), name: "Three Sisters Stew", description: "Stew made with corn, beans, and squash, a staple of many tribes." },
                { id: nanoid(), name: "Indian Tacos", description: "Frybread topped with chili, lettuce, cheese, and other toppings." },
                { id: nanoid(), name: "Venison Jerky", description: "Dried and seasoned venison meat." },
                { id: nanoid(), name: "Wild Rice Casserole", description: "Casserole dish made with wild rice, often mixed with vegetables and herbs." },
                { id: nanoid(), name: "Salmon Feast", description: "Traditional salmon preparation, often smoked or baked." },
                { id: nanoid(), name: "Pemmican", description: "Dried meat, fat, and berries, a high-energy food used by indigenous peoples." },
                { id: nanoid(), name: "Frybread Taco", description: "Frybread topped with taco fillings." },
                { id: nanoid(), name: "Blue Corn Mush", description: "Mush made from blue corn, a traditional dish in some tribes." },
                { id: nanoid(), name: "Indian Pudding", description: "Dessert made with cornmeal, molasses, and spices." },
                { id: nanoid(), name: "Fried Hominy", description: "Fried and salted hominy corn kernels." },
                { id: nanoid(), name: "Buffalo Stew", description: "Stew made with buffalo meat, vegetables, and herbs." },
                { id: nanoid(), name: "Acorn Soup", description: "Soup made from acorns, a traditional food source." },
                { id: nanoid(), name: "Fiddlehead Ferns", description: "Young, coiled fern fronds, often sautéed as a side dish." },
                { id: nanoid(), name: "Fruit Pudding", description: "Pudding made with indigenous fruits and sweeteners." },
                { id: nanoid(), name: "Bannock", description: "Flatbread, similar to frybread, often cooked over an open fire." },
                { id: nanoid(), name: "Wojapi", description: "Fruit sauce, often made with berries, served over various dishes." },
                { id: nanoid(), name: "Smoked Whitefish", description: "Whitefish smoked to perfection." },
                { id: nanoid(), name: "Chia Seed Pudding", description: "Pudding made from chia seeds soaked in liquid, often with sweeteners and fruit." },
                { id: nanoid(), name: "Squash Blossom Soup", description: "Soup made with squash blossoms and other ingredients." },
                { id: nanoid(), name: "Maple Candy", description: "Candy made from pure maple syrup." },
                { id: nanoid(), name: "Sagamite", description: "Soup or porridge made from cornmeal and beans." },
                { id: nanoid(), name: "Fried Squirrel", description: "Squirrel meat, often breaded and fried." },
                { id: nanoid(), name: "Wild Berry Salad", description: "Salad made with foraged wild berries." },
                { id: nanoid(), name: "Piki Bread", description: "Thin, paper-like bread made from blue cornmeal." },
                { id: nanoid(), name: "Frybread Pudding", description: "Dessert made from torn-up frybread mixed with sweet ingredients." },
                { id: nanoid(), name: "Cattail Shoots", description: "Young shoots of cattail plants, often used in salads." },
                { id: nanoid(), name: "Buffalo Chili", description: "Chili made with buffalo meat and spices." },
                { id: nanoid(), name: "Wild Plum Jam", description: "Jam made from wild plums, a traditional preserve." },
                { id: nanoid(), name: "Sunflower Seed Soup", description: "Soup made from ground sunflower seeds." },
            ],
}
        
export default FlavoredDishes