const disclaimerForm = [

`Disclaimer and Liability Release for EatAi\n

By using EatAi, you ("the User") acknowledge and agree to the following detailed terms and conditions:\n

1. AI-Powered Menu and Recipe Generator:\n
EatAi offers a menu and recipe generation service powered by artificial intelligence technology. The information provided by the app is generated based on available data, algorithms, and user inputs. It does not guarantee the accuracy, completeness, or suitability of the menus and recipes for any specific dietary needs, allergies, intolerances, or medical conditions.\n

2. Responsibility for Allergies, Dietary Restrictions, and Medical Conditions:\n
The User assumes full responsibility for evaluating the suitability of the menus and recipes generated by EatAi for their individual dietary preferences, restrictions, allergies, and any underlying medical conditions. The app does not verify or account for individual allergies, medical conditions, or specific dietary requirements. Users should exercise caution, cross-reference ingredients, and consult with a healthcare professional or nutritionist if they have concerns about food allergies, dietary needs, or medical conditions.\n

3. Recipe Modifications and Nutritional Information:\n
Users are solely responsible for making any necessary modifications to the recipes generated by EatAi to accommodate their dietary restrictions, allergies, preferences, and nutritional needs. Any nutritional information provided by the app is for general guidance only and should not be considered a substitute for personalized dietary advice.\n

4. No Medical or Legal Advice:\n
EatAi does not provide medical, nutritional, or legal advice. The information and recommendations offered by the app are for informational purposes only and should not be used as a replacement for professional medical, nutritional, or legal advice.\n

5. Food Safety:\n
Users must ensure the safe handling, storage, and preparation of food based on the recipes generated by the app. EatAi does not provide food safety guidance or conduct inspections. It is essential for Users to follow established food safety practices and guidelines.\n

6. Limitation of Liability:\n
EatAi, its developers, affiliates, and partners shall not be liable for any damages, losses, injuries, or adverse health effects arising from the use or misuse of the app or the recipes generated by it. This includes but is not limited to personal injury, allergic reactions, foodborne illnesses, or any other health-related issues. Users utilize the app at their own risk.\n

7. Indemnification:\n
The User agrees to indemnify and hold harmless EatAi, its developers, affiliates, and partners from any claims, liabilities, or expenses, including legal fees, arising from the User's use of the app. This includes any claims related to food allergies, dietary restrictions, or recipe modifications.\n

8. No Warranty:\n
EatAi is provided "as-is" without any warranties, expressed or implied. There are no guarantees regarding the accuracy, reliability, or suitability of the app for a particular purpose. EatAi does not warrant that the app will be error-free or uninterrupted.\n

9. Privacy and Data Security:\n
EatAi places a high priority on data privacy and security. User data will be handled in accordance with our Privacy Policy, which can be accessed on our website or within the app. Users are encouraged to review the Privacy Policy to understand how their data is collected, used, and protected.\n

10. Changes to Terms and Conditions:\n
EatAi reserves the right to modify these terms and conditions at any time. Users are encouraged to regularly review this document for updates.\n

By using EatAi, the User acknowledges that they have read, understood, and agreed to all the terms and conditions outlined in this detailed disclaimer and liability release.\n

This disclaimer and liability release are effective as of.\n`

]

export default disclaimerForm;