const carbs = [
    { "id": 0, "name": "Sweet potatoes" },
    { "id": 1, "name": "Beets" },
    { "id": 2, "name": "Parsnips" },
    { "id": 3, "name": "Rutabagas" },
    { "id": 4, "name": "Plantains" },
    { "id": 5, "name": "Butternut squash" },
    { "id": 6, "name": "Acorn squash" },
    { "id": 7, "name": "Corn on the cob" },
    { "id": 8, "name": "Carrots" },
    { "id": 9, "name": "Peas" },
    { "id": 10, "name": "Pumpkin" },
    { "id": 11, "name": "Red potatoes" },
    { "id": 12, "name": "Cassava" },
    // { "id": 13, "name": "Jerusalem artichokes" },
    { "id": 14, "name": "Taro" },
    { "id": 15, "name": "Yuca" },
    { "id": 16, "name": "Turnips" },
    { "id": 17, "name": "Gilfeather turnip" },
    { "id": 18, "name": "Hubbard squash" },
    { "id": 19, "name": "Amaranth" },
    { "id": 20, "name": "Millet" },
    { "id": 21, "name": "Sorghum" },
    { "id": 22, "name": "Barley" },
    { "id": 23, "name": "Quinoa" },
    { "id": 24, "name": "Brown rice" },
    { "id": 25, "name": "Buckwheat" },
    { "id": 26, "name": "Teff" },
    { "id": 27, "name": "Farro" },
    { "id": 28, "name": "Spelt" },
    // { "id": 29, "name": "Whole wheat couscous" },
    { "id": 30, "name": "Whole grain pasta" },
    { "id": 31, "name": "Oats" },
    { "id": 32, "name": "Pearl barley" },
    { "id": 33, "name": "Rye berries" },
    { "id": 34, "name": "Whole wheat bread" },
    { "id": 35, "name": "Whole wheat pita" },
    { "id": 36, "name": "Bulgur" },
    { "id": 37, "name": "Red lentils" },
    { "id": 38, "name": "Split peas" },
    { "id": 39, "name": "Mung beans" },
    { "id": 40, "name": "Black-eyed peas" },
    { "id": 41, "name": "Chickpeas" },
    { "id": 42, "name": "Pinto beans" },
    { "id": 43, "name": "Kidney beans" },
    // { "id": 44, "name": "Great Northern beans" },
    { "id": 45, "name": "Navy beans" },
    { "id": 46, "name": "Lima beans" },
    { "id": 47, "name": "Cannellini beans" },
    { "id": 48, "name": "White beans" },
    { "id": 49, "name": "Fava beans" }
  ]
export default carbs;
