const cookingOils = [
	{ id: 1, name: "Olive Oil" },
	{ id: 2, name: "Avocado Oil" },
	{ id: 3, name: "Coconut Oil" },
	{ id: 4, name: "Canola Oil" },
	{ id: 5, name: "Peanut Oil" },
	{ id: 6, name: "Sesame Oil" },
	{ id: 7, name: "Walnut Oil" },
	{ id: 8, name: "Flaxseed Oil" },
	{ id: 9, name: "Grapeseed Oil" },
	{ id: 10, name: "Sunflower Oil" },
	{ id: 11, name: "Safflower Oil" },
	{ id: 12, name: "Hemp Oil" },
	{ id: 13, name: "Pumpkin Seed Oil" },
	{ id: 14, name: "Almond Oil" },
	// { id: 15, name: "Rice Bran Oil" },
	{ id: 16, name: "Macadamia Nut Oil" },
	// { id: 17, name: "Corn Oil" },
	{ id: 18, name: "Black Seed Oil" },
	{ id: 19, name: "Pistachio Oil" },
	{ id: 20, name: "Red Palm Oil" },
	{ id: 21, name: "Grapeseed Oil" },
	{ id: 22, name: "Mustard Seed Oil" },
	{ id: 23, name: "Poppy Seed Oil" },
	{ id: 24, name: "Ghee (Clarified Butter)" },
	// { id: 25, name: "Argan Oil" },
];

export default cookingOils;