const healthyFats = [
    { id: 0, name: "Choose Fats" },
	{ id: 1, name: "Avocado oil" },
	{ id: 2, name: "Olive oil" },
	{ id: 3, name: "Coconut oil" },
	{ id: 4, name: "Flaxseed oil" },
	{ id: 5, name: "Chia seeds" },
	// { id: 6, name: "Fatty fish (salmon, mackerel, sardines)" },
	{ id: 7, name: "Walnuts" },
	{ id: 8, name: "Almonds" },
	{ id: 9, name: "Hazelnuts" },
	{ id: 10, name: "Macadamia nuts" },
	{ id: 11, name: "Pecans" },
	{ id: 12, name: "Brazil nuts" },
	{ id: 13, name: "Pistachios" },
	{ id: 14, name: "Cashews" },
	{ id: 15, name: "Hemp seeds" },
	{ id: 16, name: "Sunflower seeds" },
	{ id: 17, name: "Pumpkin seeds" },
	{ id: 18, name: "Sesame seeds" },
	{ id: 19, name: "Flaxseed" },
	{ id: 20, name: "Ghee" },
	{ id: 21, name: "Grass-fed butter" },
	// { id: 22, name: "Grass-fed beef tallow" },
	// { id: 23, name: "Duck fat" },
	// { id: 24, name: "Goose fat" },
	// { id: 25, name: "Cocoa butter" },
	// { id: 26, name: "Dark chocolate (in moderation)" },
	// { id: 27, name: "Fatty cuts of meat (e.g., fatty fish, ribeye steak)" },
	{ id: 28, name: "Full-fat yogurt (with live cultures)" },
	{ id: 29, name: "Full-fat kefir" },
	{ id: 30, name: "Full-fat cottage cheese" },
	// { id: 31, name: "Cheese (in moderation)" },
	{ id: 32, name: "Eggs (including the yolk)" },
	{ id: 33, name: "Fatty cuts of poultry (e.g., chicken thighs)" },
	{ id: 34, name: "Pork fat (lard)" },
	{ id: 35, name: "Flaxseed meal" },
	{ id: 36, name: "Safflower oil" },
	// { id: 37, name: "Algal oil (from algae)" },
	// { id: 38, name: "Fish oil supplements (omega-3)" },
	{ id: 39, name: "Krill oil" },
	{ id: 40, name: "Walnut oil" },
	{ id: 41, name: "Sesame oil" },
	{ id: 42, name: "Pistachio oil" },
	{ id: 43, name: "Almond oil" },
	{ id: 44, name: "Hazelnut oil" },
	{ id: 45, name: "Macadamia nut oil" },
	{ id: 46, name: "Pumpkin seed oil" },
	{ id: 47, name: "Sunflower oil" },
	{ id: 48, name: "Rice bran oil" },
	{ id: 49, name: "Peanut oil (in moderation)" },
];

export default healthyFats;