const fruitsArr = [
	{ id: 1, name: "Apples" },
	{ id: 2, name: "Bananas" },
	{ id: 3, name: "Oranges" },
	{ id: 4, name: "Blueberries" },
	{ id: 5, name: "Strawberries" },
	{ id: 6, name: "Kiwi" },
	{ id: 7, name: "Papaya" },
	{ id: 8, name: "Watermelon" },
	{ id: 9, name: "Mango" },
	{ id: 10, name: "Pineapple" },
	{ id: 11, name: "Avocado" },
	{ id: 12, name: "Grapefruit" },
	{ id: 13, name: "Pomegranate" },
	{ id: 14, name: "Cranberries" },
	{ id: 15, name: "Cherries" },
	{ id: 16, name: "Raspberries" },
	{ id: 17, name: "Blackberries" },
	{ id: 18, name: "Lemon" },
	{ id: 19, name: "Lime" },
	{ id: 20, name: "Guava" },
	{ id: 21, name: "Apricot" },
	{ id: 22, name: "Peach" },
	{ id: 23, name: "Plums" },
	{ id: 24, name: "Figs" },
	{ id: 25, name: "Grapes" },
	{ id: 26, name: "Cantaloupe" },
	{ id: 27, name: "Passion fruit" },
	{ id: 28, name: "Dragon fruit" },
	{ id: 29, name: "Lychee" },
	{ id: 30, name: "Tangerines" },
	{ id: 31, name: "Clementines" },
	{ id: 32, name: "Elderberries" },
	{ id: 33, name: "Acerola cherries" },
	{ id: 34, name: "Black currants" },
	{ id: 35, name: "Goji berries" },
	{ id: 36, name: "Mulberries" },
	{ id: 37, name: "Starfruit" },
	// { id: 38, name: "Persimmon" },
	{ id: 39, name: "Boysenberries" },
	{ id: 40, name: "Papaya)" },
	{ id: 41, name: "Huckleberries" },
	{ id: 42, name: "Gooseberries" },
	// { id: 43, name: "Kiwano (African horned melon)" },
	{ id: 44, name: "Jackfruit" },
	{ id: 45, name: "Red currants" },
	{ id: 46, name: "Nectarines" },
	{ id: 47, name: "Kumquats" },
	// { id: 48, name: "Rambutan" },
	// { id: 49, name: "Longan" },
	// { id: 50, name: "Jabuticaba" },
];

export default fruitsArr;