const proteinArray = [
	{ id: 0, name: "Choose Proteins" },
	{ id: 1, name: "Chicken breast" },
	{ id: 2, name: "Chicken dark meat" },
	{ id: 3, name: "Salmon" },
	{ id: 4, name: "Tuna" },
	{ id: 5, name: "Beef (steak)" },
	{ id: 6, name: "Beef (filet)" },
	{ id: 7, name: "Beef (sirloin)" },
	{ id: 8, name: "Ground beef (90/10)" },
	{ id: 9, name: "Ground beef (85/15)" },
	{ id: 10, name: "Ground beef (80/20)" },
	{ id: 11, name: "Eggs" },
	{ id: 12, name: "Pork (chops)" },
	{ id: 13, name: "Turkey" },
	{ id: 14, name: "Shrimp" },
	{ id: 15, name: "Tilapia" },
	{ id: 16, name: "Cod" },
	{ id: 17, name: "Tofu" },
	{ id: 18, name: "Lamb" },
	{ id: 19, name: "Sardines" },
	{ id: 20, name: "Quinoa" },
	{ id: 21, name: "Duck" },
	{ id: 22, name: "Crab" },
	{ id: 23, name: "Bison" },
	{ id: 24, name: "Halibut" },
	{ id: 25, name: "Scallops" },
	{ id: 26, name: "Mussels" },
	{ id: 27, name: "Venison" },
	{ id: 28, name: "Tempeh" },
	{ id: 29, name: "Swordfish" },
	{ id: 30, name: "Mahi-Mahi" },
	{ id: 31, name: "Catfish" },
	{ id: 32, name: "Oysters" },
	{ id: 33, name: "Haddock" },
	{ id: 34, name: "Anchovies" },
	{ id: 35, name: "Snapper" },
	{ id: 36, name: "Rabbit" },
	{ id: 37, name: "Crawfish" },
	{ id: 38, name: "Herring" },
	{ id: 39, name: "Flounder" },
	{ id: 40, name: "Ground beef (90/10)" },
	{ id: 41, name: "Ground beef (85/15)" },
	{ id: 42, name: "Ground beef (80/20)" },
	{ id: 43, name: "Octopus" },
	{ id: 44, name: "Clams" },
	{ id: 45, name: "Kangaroo" },
	{ id: 46, name: "Veal" },
	{ id: 47, name: "Elk" },
	{ id: 48, name: "Grouper" },
	{ id: 49, name: "Pheasant" },
	{ id: 50, name: "Alligator" },
	{ id: 51, name: "Bison" },
	{ id: 52, name: "Emu" },
	{ id: 53, name: "Quail" },
	{ id: 54, name: "Rattlesnake" },
	{ id: 55, name: "Abalone" },
	{ id: 56, name: "Turtle" },
	{ id: 57, name: "Goose" },
	{ id: 58, name: "Llama" },
];
export default proteinArray;
