const proteinArray = [
  { id: 0, name: "Chicken breast" },
  { id: 1, name: "Chicken dark meat" },
  { id: 2, name: "Salmon" },
  { id: 3, name: "Tuna" },
  { id: 4, name: "Beef (steak)" },
  { id: 5, name: "Beef (filet)" },
  { id: 6, name: "Beef (sirloin)" },
  { id: 7, name: "Ground beef (90/10)" },
  { id: 8, name: "Ground beef (85/15)" },
  { id: 9, name: "Ground beef (80/20)" },
  { id: 10, name: "Eggs" },
  { id: 11, name: "Pork (chops)" },
  { id: 12, name: "Turkey" },
  { id: 13, name: "Shrimp" },
  { id: 14, name: "Tilapia" },
  { id: 15, name: "Cod" },
  { id: 16, name: "Tofu" },
  { id: 17, name: "Lamb" },
  { id: 18, name: "Sardines" },
  { id: 19, name: "Quinoa" },
  { id: 20, name: "Duck" },
  { id: 21, name: "Crab" },
  { id: 22, name: "Bison" },
  { id: 23, name: "Halibut" },
  { id: 24, name: "Scallops" },
  { id: 25, name: "Mussels" },
  { id: 26, name: "Venison" },
  { id: 27, name: "Tempeh" },
  { id: 28, name: "Swordfish" },
  { id: 29, name: "Mahi-Mahi" },
  { id: 30, name: "Catfish" },
  { id: 31, name: "Oysters" },
  { id: 32, name: "Haddock" },
  { id: 33, name: "Anchovies" },
  { id: 34, name: "Snapper" },
  { id: 35, name: "Rabbit" },
  { id: 36, name: "Crawfish" },
  { id: 37, name: "Herring" },
  { id: 38, name: "Flounder" },
  { id: 39, name: "Ground beef (90/10)" },
  { id: 40, name: "Ground beef (85/15)" },
  { id: 41, name: "Ground beef (80/20)" },
  { id: 42, name: "Octopus" },
  { id: 43, name: "Clams" },
  { id: 44, name: "Kangaroo" },
  { id: 45, name: "Veal" },
  { id: 46, name: "Elk" },
  { id: 47, name: "Grouper" },
  { id: 48, name: "Pheasant" },
  { id: 49, name: "Alligator" },
  { id: 50, name: "Bison" },
  { id: 51, name: "Emu" },
  { id: 52, name: "Quail" },
  { id: 53, name: "Rattlesnake" },
  { id: 54, name: "Abalone" },
  { id: 55, name: "Turtle" },
  { id: 56, name: "Goose" },
  { id: 57, name: "Llama" },
];
export default proteinArray;