const vegetables = {
  veg: [
    { id: 0, name: "Potato" },
    { id: 1, name: "Onion" },
    { id: 2, name: "Carrot" },
    { id: 3, name: "Cucumber" },
    { id: 4, name: "Lettuce" },
    { id: 5, name: "Bell pepper" },
    { id: 6, name: "Broccoli" },
    { id: 7, name: "Spinach" },
    { id: 8, name: "Cauliflower" },
    { id: 9, name: "Zucchini" },
    { id: 10, name: "Eggplant" },
    { id: 11, name: "Green beans" },
    { id: 12, name: "Sweet potato" },
    { id: 13, name: "Cabbage" },
    { id: 14, name: "Kale" },
    { id: 15, name: "Brussels sprouts" },
    { id: 16, name: "Radish" },
    { id: 17, name: "Celery" },
    { id: 18, name: "Asparagus" },
    { id: 19, name: "Peas" },
    { id: 20, name: "Corn" },
    { id: 21, name: "Mushrooms" },
    { id: 22, name: "Garlic" },
    { id: 23, name: "Beets" },
    { id: 24, name: "Leeks" },
    { id: 25, name: "Artichoke" },
    { id: 26, name: "Okra" },
    { id: 27, name: "Swiss chard" },
    { id: 28, name: "Pumpkin" },
    { id: 29, name: "Butternut squash" },
    { id: 30, name: "Turnip" },
    { id: 31, name: "Watercress" },
    { id: 32, name: "Snow peas" },
    { id: 33, name: "Fennel" },
    { id: 34, name: "Rutabaga" },
    { id: 35, name: "Collard greens" },
    { id: 36, name: "Arugula" },
    { id: 37, name: "Bok choy" },
    { id: 38, name: "Mustard greens" },
    { id: 39, name: "Escarole" },
    { id: 40, name: "Cilantro (coriander)" },
    { id: 41, name: "Dill" },
    { id: 42, name: "Parsley" },
    { id: 43, name: "Thyme" },
    { id: 44, name: "Rosemary" },
    { id: 45, name: "Sage" },
    { id: 46, name: "Basil" },
    { id: 47, name: "Mint" },
    { id: 48, name: "Chives" },
    { id: 49, name: "Green onions (scallions)" },
    { id: 50, name: "Red onion" },
    { id: 51, name: "Shallots" },
    { id: 52, name: "Ginger" },
    { id: 53, name: "Turmeric" },
    { id: 54, name: "Horseradish" },
    { id: 55, name: "Celeriac (celery root)" },
    { id: 56, name: "Jicama" },
    { id: 57, name: "Kohlrabi" },
    { id: 58, name: "Jerusalem artichoke" },
    { id: 59, name: "Bamboo shoots" },
    { id: 60, name: "Water chestnuts" },
    { id: 61, name: "Daikon radish" },
    { id: 62, name: "Endive" },
    { id: 63, name: "Radicchio" },
    { id: 64, name: "Chinese cabbage" },
    { id: 65, name: "Napa cabbage" },
    { id: 66, name: "Turnip greens" },
    { id: 67, name: "Collard greens" },
    { id: 68, name: "Purslane" },
    { id: 69, name: "Plantains" },
    { id: 70, name: "Yuca (cassava)" },
    { id: 71, name: "Taro" },
    { id: 72, name: "Chayote" },
    { id: 73, name: "Acorn squash" },
    { id: 74, name: "Hubbard squash" },
    { id: 75, name: "Sunchoke (Jerusalem artichoke)" },
    { id: 76, name: "Radish greens" },
    { id: 77, name: "Chicory" },
    { id: 78, name: "Amaranth leaves" },
    { id: 79, name: "Komatsuna" },
    { id: 80, name: "Tatsoi" },
    { id: 81, name: "Malabar spinach" },
    { id: 82, name: "Sorrel" },
    { id: 83, name: "Water spinach (kangkong)" },
    { id: 84, name: "Lotus root" },
    { id: 85, name: "Mung bean sprouts" },
    { id: 86, name: "Alfalfa sprouts" },
    { id: 87, name: "Bamboo shoots" }
  ]
}
export default vegetables